OpenLitterMap/react-native

- assets/langs/es/litter.json
some extra translations in category Sanitary
> some extra translations

- screens/pages/CameraPage.js
This addresses Issue #12 
I added a simple animated black layer over the top of the camera page, to create a shutter effect when you take a picture. 
(Similar to the standard camera app on iOS & Android)
> Added camera shutter effect

- reducers/gallery_reducer.js
Append new user selected gallery photos, instead of replace
> Willalexander bugfix/photo gallery selection append

- ios/Podfile.lock
- screens/pages/CameraPage.js
fix issue #53 - showing no permission even when permission granted
> fix: camera permission issue 

- actions/settings_actions.js
- screens/pages/SettingsComponent.js
fixed #57 
- fixed issue of type value not passed as params
- and data not passed in body
- and keys should be capitalised i.e Name, Username, Email --> lowercase was sent earlier
> fix: not able to save myaccount data

- App.js
- screens/SwipeScreen.js
- screens/pages/CameraPage.js
fix #49 
Render RNCamera only when page not focused
> fix: app continuously accessing camera

- App.js
- actions/settings_actions.js
- actions/types.js
- assets/langs/en/settings.json
- reducers/settings_reducer.js
- screens/pages/SettingsComponent.js
- error / success message shown when setting updated
- modal redesigned
> feat: show error message on data not edited

- screens/pages/AddTags.js
- screens/pages/components/LitterBottomSearch.js
fix: issue of image not deleting when deleting from  AddTags page using X button.
- the issue was image were not removed from asyncstorage
> fix: issue of image not deleting and using X button

- assets/langs/ar/user.json
- assets/langs/de/user.json
- assets/langs/es/user.json
- assets/langs/fr/user.json
- assets/langs/nl/user.json
- assets/langs/pt/user.json
[trello card](https://trello.com/c/sKUFXPvc)
> translation change next littercoin

- actions/gallery_actions.js
- screens/home/HomeScreen.js
- screens/home/homeComponents/UploadImagesGrid.js
- added null checks on gallery and upload photo
- added location pin on images with lat/lon
> fix: adding null checks on lat/lon

- actions/auth_actions.js
- reducers/auth_reducer.js
- fixes error [undefined is not an object (evaluating 't.response.status')](https://trello.com/c/Wr2JXX0M)
- use async/await
> Refactor and handling network error on login

- actions/shared_actions.js
- screens/components/theme/colors.js
- screens/home/HomeScreen.js
- utils/isGeotagged.js
- handles [issue # OPENLITTERMAP-4H](https://sentry.io/organizations/openlittermap/issues/2627739018/?project=1761567&query=is%3Aunresolved&statsPeriod=14d)
- fixes [issue # OPENLITTERMAP-35](https://sentry.io/organizations/openlittermap/issues/2407224592/?project=1761567&query=is%3Aunresolved&statsPeriod=14d)
**Note**
Working on better uploading screen -- will release with unified api (photo + tags in one api)
for this PR I rolled back the new changes -- as it will take some time and needs better testing.
Merge conflicts may occur while merging #92 and this PR to staging
dont merge if that happens I will resolve the conflict.
> fix: image upload error handling

- screens/home/HomeScreen.js
fix for [sentry issue OPENLITTERMAP-4J](https://sentry.io/organizations/openlittermap/issues/2635322237/?project=1761567&query=is%3Aunresolved&statsPeriod=14d)
> fix: added img.tags check & undefined check

- android/app/build.gradle
Fixing numbers not having commas issue on android
> fix: getLocaleString issue on android

- screens/home/HomeScreen.js
lon field was commented for testing and forgot to revert back.
Please test the full flow of app on Camera, Gallery And web photo before uploading app.
@xlcrr this PR needs to be merged before app release.
> fix: uncomment Lon field

- screens/SettingsScreen.js
issue was show_name and show_username had boolean values and rest had 0 || 1
> fix: privacy switch not working

- screens/auth/AuthScreen.js
Replaced [legacy string ref with createRef](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs)
fix [sentry bug - 58](https://sentry.io/organizations/openlittermap/issues/2729335150/?project=1761567&query=is%3Aunresolved)
> fix: remove legacy string ref

- actions/images_action.js
- actions/types.js
- actions/web_actions.js
- reducers/images_reducer.js
- screens/gallery/galleryComponents/AlbumList.js
- screens/home/HomeScreen.js
- screens/pages/AddTags.js
- screens/pages/components/LitterBottomSearch.js
- change `addTagsToImages` to `addTagToImage`
- change `ADD_TAGS_TO_IMAGE` to `ADD_TAG_TO_IMAGE`
- change `images` to `imagesArray` in state
**Trello**
[Make suggested changes from PR review of #129](https://trello.com/c/FJz9Ru23)
> feat: change recommended changes in #129

- assets/data/litterkeys.js
- assets/langs/ar/litter.json
- assets/langs/de/litter.json
- assets/langs/en/litter.json
- assets/langs/es/litter.json
- assets/langs/fr/litter.json
- assets/langs/nl/litter.json
- assets/langs/pt/litter.json
Added new tag
- `chewing gum` with translation
- `pizza box` with translation
**Trello**
[Food: Chewing Gum](https://trello.com/c/FNguckNo)
[Pizza Box](https://trello.com/c/M3QU41Gv)
> feat: added tags chewing gum & pizza box

- actions/gallery_actions.js
- actions/images_action.js
- screens/home/HomeScreen.js
Rename `uploadTags` to `uploadTagsToWebImage`
> fix: review changes for #116

- screens/gallery/GalleryScreen.js
- screens/home/HomeScreen.js
- fix wrong month shown on GalleryScreen
[Wrong month name shown on gallery screen](https://trello.com/c/IADbo3di)
> fix: wrong month shown on gallery screen

- screens/auth/authComponents/SignupForm.js
> Change username icon on auth screen

- actions/images_action.js
- actions/types.js
- reducers/images_reducer.js
- screens/setting/SettingsScreen.js
When user change default litter status. Change status on old image after confirmation
[Trello Board](https://trello.com/c/wv7Jovxw)
> feat: litter status change on all images on global setting change

- screens/home/homeComponents/UploadImagesGrid.js
- Added container padding so that last image is selectable, and not blocked by Upload button
[Add margin to bottom photos to make all images selectable and not blocked by upload button](https://trello.com/c/F3dNUzcJ)
> fix: add container padding on homescreen

- reducers/images_reducer.js
- screens/addTag/AddTags.js
- screens/addTag/addTagComponents/LitterTagsCard.js
- This PR fixes the app crash caused by deleting an image from middle of Swiper.
[Issue with deleting images. App hangs --  tags shift to prev image](https://trello.com/c/gZdGAw3g)
> Fix issue of app crashing after delete from swiper

- assets/langs/de/tag.json
- assets/langs/en/tag.json
- assets/langs/es/tag.json
- assets/langs/fr/tag.json
- assets/langs/nl/tag.json
- assets/langs/pt/tag.json
- reducers/images_reducer.js
- screens/addTag/addTagComponents/LitterBottomSearch.js
- When typing to suggest tags, and there are no suggestions, now it shows the most recently selected tags 
[Trello](https://trello.com/c/IU1H1wPF)
> feat: initially show previous tags as suggested tags

- reducers/images_reducer.js
- Show last added tag at the beginning of suggested tags for better usability.
[Show last used tag at the beginning of suggested tags](https://trello.com/c/xFbN5A8k)
> feat: show last used tag to start of prev used tags

- actions/images_action.js
- screens/addTag/AddTags.js
- screens/addTag/addTagComponents/LitterTagsCard.js
- Fix the issue of app crash when only single web image is present & it's deleted from swiper delete
[App crash on deleting Web Images from Swiper](https://trello.com/c/W0yH67l0)
> fix: app crash on web image delete

- screens/addTag/AddTags.js
- screens/addTag/addTagComponents/LitterPickerWheels.js
- make Add Tags Action sheet transparent
> feat: transparent AddTags Action Sheet

- screens/addTag/addTagComponents/LitterTagsCard.js
- Fix the issue of tags overflowing when lot of tags are added, by adding scrollview
- This is experimental update.
[LitterTag Card have tags overflowing](https://trello.com/c/HdsuQ1Rf/140-littertag-card-have-tags-overflowing)
https://user-images.githubusercontent.com/26044934/148383311-d720f312-f3e3-4c4d-9f1f-d765970a1a61.mov
> feat: make litter tag card height extendable

- screens/addTag/addTagComponents/LitterImage.js
- Changed image resizeMode to `contain` from `cover`
> Show full image when tagging

- actions/shared_actions.js
- actions/types.js
- reducers/shared_reducer.js
- routes/mainRoutes.js
- screens/addTag/AddTags.js
- screens/addTag/addTagComponents/LitterBottomSearch.js
- screens/addTag/addTagComponents/LitterImage.js
- screens/addTag/addTagComponents/LitterTagsCard.js
- screens/home/HomeScreen.js
- screens/home/homeComponents/UploadImagesGrid.js
rn-gesture-handler not working on Modal and Stack navigation https://github.com/software-mansion/react-native-gesture-handler/issues/139
- Changed the modal to a screen
- fix image deletion error because of the changes
[Android Zoom issue](https://trello.com/c/jU9DDV1G)
> fix: android zoom image issue

- screens/addTag/AddTags.js
- removed move image button and fn
**Trello**
[Remove "move image" button when tagging](https://trello.com/c/Vwa2PUDv)
> feat: remove move image button

- actions/gallery_actions.js
- screens/gallery/GalleryScreen.js
- fix: remove videos from gallery screen and only show images
- fix: issue of images not showing in reverse chronological order after initial load.
**Trello**
[Gallery images not in correct order](https://trello.com/c/6Qn0vAPN)
> fix: gallery image order issues

- actions/types.js
- assets/data/litterkeys.js
- assets/langs/ar/litter.json
- assets/langs/de/litter.json
- assets/langs/en/litter.json
- assets/langs/es/litter.json
- assets/langs/fr/litter.json
- assets/langs/nl/litter.json
- assets/langs/pt/litter.json
Added brand tags
- Tim Hortons
- Wendys
**Trello**
[Brand Tags](https://trello.com/c/h3IMsNGn)
> New brand Tags

- screens/addTag/addTagComponents/LitterBottomSearch.js
- screens/addTag/addTagComponents/LitterPickerWheels.js
- screens/addTag/addTagComponents/LitterTags.js
- Reduced margin below customtags/search textfield
**Trell**
[Reduce margin](https://trello.com/c/TcPnSMpl)
> fix: margins below textfield in addTags screen

- screens/setting/SettingsScreen.js
- PR to show version number in settings screen.
**Trello**
[Include version on settings page](https://trello.com/c/aaRdPXMS)
> feat: show version number

- actions/settings_actions.js
- package-lock.json
- package.json
- screens/setting/SettingsScreen.js
PR to set `global_flag`
**Note**
- Need to success modal, will add it together with  username, name etc success modal change.
**Trello**
[Add: Choose country flag on settings](https://trello.com/c/gEacJ6fw)
https://user-images.githubusercontent.com/26044934/175116249-4c69200b-03f3-4a54-9cc4-73dc5349cc34.mov
> Set country

- screens/home/HomeScreen.js
- fix the issue of not able to cancel uploads.
**TRELLO**
[Cancel not working](https://trello.com/c/XWD8BhTt)
> fix: cancel upload not working

- screens/components/textInput/CustomTextInput.js
- fix the bug where textfield height was fixed making text cut off on some devices
> fix: textfield height
