screens/pages/components/LitterBottomSearch.js
I am only clearing the text field not resetting the suggested tags.
As one may type "bottle" and want to select multiple type of bottles , so if we reset suggestions user will have to type again
=> fix #4 : clears text field after one tag is selected

reducers/auth_reducer.js, screens/camera/CameraScreen.js, screens/components/AnimatedCircle.js, screens/components/card/IconStatsCard.js, screens/components/card/StatsGrid.js, screens/userStats/UserStatsScreen.js, screens/userStats/_components/ProgressCircleCard.js, screens/userStats/_components/ProgressStatCard.js, screens/userStats/_components/index.js
- added circular progress for both xp and littercoin in userstats page [trello card](https://trello.com/c/R2R0fzHh)
- added ordinal to rank -- now rank shows like 1st , 2nd etc  [trello card ](https://trello.com/c/EXkphqr4)
- fixed the issue of locationSubscription() not a fn  [trello card ](https://trello.com/c/48Tz6QGM)
**Note**
- for level and littercoin the count for animation starts from 0 . because it looked better with animating circle
=> Littercoin progress circle

actions/types.js, screens/SettingsScreen.js, screens/components/Header.js, screens/gallery/GalleryScreen.js
- Added props to control styling of left, centre, and right container of header.
- Fix header styling issues of Geotagged and setting screen
- Tested on iphone 8
=> fix: header stying issues on settings and geotagged screen

actions/types.js, screens/camera/CameraScreen.js
- Fixes the bug `camera.takePicture [TypeError: input.charCodeAt is not a function. (In 'input.charCodeAt(i++)', 'input.charCodeAt' is undefined)]` on android.
- Android --> `"filename": "dca976b5-5098-4894-bf8e-d717feb291c8.jpg"`
- IOS --> `"filename": "6163ADDE-2DE3-45E3-B71D-CBE4D37C716D.jpg"`
[Android filename bug on taking images from OLM camera](https://trello.com/c/eixjsAMv)
=> fix: android filename issue

.gitignore, actions/types.js, ios/Podfile.lock, package-lock.json, package.json
- upgraded package react-native-device-info
- Usage of Deviceinfo.getModel() will be removed in Add Tags redesign in next release. This is a quick fix till then
[DeviceInfo.getModel() not working on some models](https://trello.com/c/NUY2wPeL)
[undefined is not an object (evaluating 't.includes')](https://trello.com/c/l7ZF0GBz)
=> Fix deviceinfo undefined error

ios/openlittermap/Info.plist
Disabled system default dark mode on ios.
**Trello**
[Darkmode colour bug on iOS Login](https://trello.com/c/LRPno0mh)
=> disable dark mode on ios

screens/addTag/AddTags.js, screens/addTag/addTagComponents/LitterTagsCard.js, screens/addTag/addTagComponents/TagsActionButton.js, screens/addTag/addTagComponents/index.js
- Show current index / total images on AddTags screen
- Shows all icons, options, tags, litter status on the selected image by default
- New card that shows selected tags on image below litter status
[Show index / total photos somewhere](https://trello.com/c/djseRcxJ)
[Show all icons, options, tags, litter status on the selected image by default](https://trello.com/c/KNe0ssjc)
[New card to show tags on image](https://trello.com/c/sz5seox3)
=> feat: show current index of image

screens/addTag/AddTags.js
- Added a button next to Add Tag button that moves image up and down for better viewing.
- Long press button to hide Categories and Tag bottom sheet
[2nd Button next to Add Tag](https://trello.com/c/3laxzIP8)
=> Button to move image up 

screens/addTag/AddTags.js
- Reduce bottom margin for ADD Tag button on android
[Android / small screens AddTags screen](https://trello.com/c/grdlBRlW)
=> fix: reduce margin of buttons on android

screens/addTag/addTagComponents/LitterBottomSearch.js
- This PR fixes the issue of `Error Translation` on adding a tag from tag picker wheel (without scrolling) after adding a tag from suggested/searched tags.
- Issue caused by old code which was not deleted after refactor.
[Translation Error after doing Search and add tag](https://trello.com/c/IFX6GzMh)
=> fix: translation error after adding tags from suggested tags

screens/addTag/AddTags.js, screens/addTag/addTagComponents/LitterBottomSearch.js, screens/addTag/addTagComponents/LitterCategories.js, screens/addTag/addTagComponents/LitterTags.js
- Fixed padding issue on littercategories scrollview
- Fixed padding issues on tags and suggested tags scrollviews
- Add white background on Suggested Tags text for better readability
**Trello Cards**
[Add padding to the end of categories Flatlist](https://trello.com/c/SQ1rl0zC)
[Suggested Tag text not visible](https://trello.com/c/57eOejgc)
=> fix: padding issues on scrollviews

package-lock.json, package.json
- react-native-cameraroll only fetches initial images `after` option not working.  https://github.com/react-native-cameraroll/react-native-cameraroll/issues/359
- Used a fork of package with fix for the issue.
**Trello**
[Android issues](https://trello.com/c/jU9DDV1G)
=> fix: Cameraroll pkg fetching initial images only android SDK30 

screens/team/teamComponents/MemberCard.js, screens/team/teamComponents/RankingMedal.js, screens/team/teamComponents/TeamListCard.js
- Center align medals in top teams.
- Added margin below `Top Teams`
- Fix `invalid date` error in last activity of member card
**Trello**
[Improvements to Teams](https://trello.com/c/ICrqr5eI)
=> Team fixes

screens/team/TeamDetailsScreen.js, screens/team/TeamLeaderboardScreen.js, screens/team/teamComponents/TeamTitle.js, screens/team/teamComponents/index.js
- added team name and copy identifier fn on team leaderboard screen
**Trello**
[In the Team leaderboard, show the Team name + copy key icon again](https://trello.com/c/ZhmALTF0)
=> feat: adding team title on leaderboard screen

screens/addTag/AddTags.js
- on opening image tagging section is shown right away, and on tap meta screen is shown.
**Trello**
[When we select an image for tagging, start tagging right away instead of the metadata screen. Tap image once to switch to metadata page](https://trello.com/c/30pzCCb1)
https://user-images.githubusercontent.com/26044934/164746268-986b9322-d4f8-41e5-864d-8c4b57ddd432.mov
=> feat: open tagging container initially on image open

actions/types.js, screens/addTag/AddTags.js
- Animate category container after navigation transition is completed.
**Trello**
[When you open an image for tagging, display the containers with an animation](https://trello.com/c/Omcj7wj4)
https://user-images.githubusercontent.com/26044934/165118289-a64f6e7e-16ab-4ebf-a065-4e4d3c3923b0.mov
=> fix: animate category container after navigation transition is completed

screens/addTag/AddTags.js, screens/addTag/addTagComponents/LitterImage.js
- Press and hold image to hide all the tagging containers
**Trello**
[When we press and hold the image, it would be nice to hide all containers](https://trello.com/c/tS006tMo)
https://user-images.githubusercontent.com/26044934/165237818-69ccf2cf-a2e8-491b-9682-ddf2311f7490.mov
=> feat: press and hold image to hide all tagging containers

actions/auth_actions.js, actions/images_action.js
- Adding user context to sentry logs. Helpful is identifying the user who faced the issue.
- Logging image upload errors to sentry
We will be able to see image upload error logs API like this in sentry.
**Trello**
[Improve logging](https://trello.com/c/6lBFpiCb)
=> feat: sentry image upload logs

reducers/auth_reducer.js, screens/userStats/UserStatsScreen.js
- PR to user user.xp_redis instead of user.xp for showing XP in app.
**Trello**
[Drop user.xp and use redis values for XP](https://trello.com/c/jN1umVCR)
=> fix: use xp_redis instead of xp

screens/gallery/GalleryScreen.js, screens/gallery/galleryComponents/AnimatedImage.js
PR to add animation when selecting image in gallery screen, and solves the issue mentioned by users about hard to identify which image is selected.
**Trello**
[Gallery image select  geolocation and selected icons are confusing for some users.](https://trello.com/c/hhnNs9ne)
https://user-images.githubusercontent.com/26044934/172699155-7f58773b-2724-44aa-8def-4563569d4957.mov
=> feat: animate image on select in gallery
